oas3-missing-example:
  # These examples are provided via schemas
  - $.paths['/product-list-page'].get.responses['200'].content['application/json']
  - $.paths['/product-list-page/more-products'].get.responses['200'].content['application/json']
